name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Copy backend folder
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "server/"
          target: "/home/${{ secrets.EC2_USER }}/backend"

      - name: Run backend on EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/${{ secrets.EC2_USER }}/backend
            npm install
            npm run build
            if ! command -v pm2 &> /dev/null
            then
              sudo npm install -g pm2
            fi
            pm2 delete backend || true
            pm2 start dist/server.js --name backend
            pm2 save
